[emacs-anzu]
src.git = "https://github.com/emacsorphanage/anzu"
src.branch = "master"
fetch.github = "emacsorphanage/anzu"

[emacs-consult]
src.git = "https://github.com/minad/consult"
src.branch = "main"
fetch.github = "minad/consult"

[emacs-consult-ghq]
src.git = "https://github.com/tomoya/consult-ghq"
src.branch = "main"
fetch.github = "tomoya/consult-ghq"

[emacs-copilot]
src.git = "https://github.com/copilot-emacs/copilot.el"
src.branch = "main"
fetch.github = "copilot-emacs/copilot.el"

[emacs-corfu]
src.git = "https://github.com/minad/corfu"
src.branch = "main"
fetch.github = "minad/corfu"

[emacs-corfu-terminal]
src.git = "https://codeberg.org/akib/emacs-corfu-terminal"
src.branch = "master"
fetch.git = "https://codeberg.org/akib/emacs-corfu-terminal"

[emacs-css-in-js-mode]
src.git = "https://github.com/orzechowskid/tree-sitter-css-in-js"
src.branch = "main"
fetch.github = "orzechowskid/tree-sitter-css-in-js"

[emacs-eglot-booster]
src.git = "https://github.com/jdtsmith/eglot-booster"
src.branch = "main"
fetch.github = "jdtsmith/eglot-booster"

[emacs-devil]
src.git = "https://github.com/susam/devil"
src.branch = "main"
fetch.github = "susam/devil"

[emacs-flymake-popon]
src.git = "https://codeberg.org/akib/emacs-flymake-popon"
src.branch = "master"
fetch.git = "https://codeberg.org/akib/emacs-flymake-popon"

[emacs-magit]
src.git = "https://github.com/magit/magit"
src.branch = "main"
fetch.github = "magit/magit"

[emacs-modus-themes]
src.git = "https://github.com/protesilaos/modus-themes"
src.branch = "main"
fetch.github = "protesilaos/modus-themes"

[emacs-moody]
src.git = "https://github.com/tarsius/moody"
src.branch = "main"
fetch.github = "tarsius/moody"

[emacs-nerd-icons-dired]
src.git = "https://github.com/rainstormstudio/nerd-icons-dired"
src.branch = "main"
fetch.github = "rainstormstudio/nerd-icons-dired"

[emacs-nix-mode]
src.git = "https://github.com/NixOS/nix-mode"
src.branch = "master"
fetch.github = "NixOS/nix-mode"

[emacs-orderless]
src.git = "https://github.com/oantolin/orderless"
src.branch = "master"
fetch.github = "oantolin/orderless"

[emacs-org-modern-indent]
src.git = "https://github.com/jdtsmith/org-modern-indent"
src.branch = "main"
fetch.github = "jdtsmith/org-modern-indent"

[emacs-projectile]
src.git = "https://github.com/bbatsov/projectile"
src.branch = "master"
fetch.github = "bbatsov/projectile"

[emacs-rg]
src.git = "https://github.com/dajva/rg.el"
src.branch = "master"
fetch.github = "dajva/rg.el"

[emacs-setup]
src.git = "https://git.sr.ht/~pkal/setup"
src.branch = "master"
fetch.git = "https://git.sr.ht/~pkal/setup"

[emacs-tsx-mode]
src.git = "https://github.com/orzechowskid/tsx-mode.el"
src.branch = "main"
fetch.github = "orzechowskid/tsx-mode.el"

[emacs-undohist]
src.git = "https://github.com/emacsorphanage/undohist"
src.branch = "master"
fetch.github = "emacsorphanage/undohist"

[emacs-vertico]
src.git = "https://github.com/minad/vertico"
src.branch = "main"
fetch.git = "https://github.com/minad/vertico"

[emacs-vundo]
src.git = "https://github.com/casouri/vundo"
src.branch = "master"
fetch.github = "casouri/vundo"
